export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <main lang="en">
      <div>{children}</div>
    </main>
  )
}
